version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/"
    schedule:
      interval: "monthly"
